[book]
title = "Документация"
authors = ["Автор"]
language = "ru"

[build]
build-dir = "book"

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []